/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_jay_computer_alu_MathUtils */

#ifndef _Included_cn_jay_computer_alu_MathUtils
#define _Included_cn_jay_computer_alu_MathUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_jay_computer_alu_MathUtils
 * Method:    longToByteArray
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_cn_jay_computer_alu_MathUtils_longToByteArray
  (JNIEnv *, jclass, jlong);

/*
 * Class:     cn_jay_computer_alu_MathUtils
 * Method:    byteArrayToLong
 * Signature: ([B)J
 */
JNIEXPORT jlong JNICALL Java_cn_jay_computer_alu_MathUtils_byteArrayToLong
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     cn_jay_computer_alu_MathUtils
 * Method:    doubleToByteArray
 * Signature: (D)[B
 */
JNIEXPORT jbyteArray JNICALL Java_cn_jay_computer_alu_MathUtils_doubleToByteArray
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     cn_jay_computer_alu_MathUtils
 * Method:    byteArrayToDouble
 * Signature: ([B)D
 */
JNIEXPORT jdouble JNICALL Java_cn_jay_computer_alu_MathUtils_byteArrayToDouble
  (JNIEnv *, jclass, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
